In [1]:
import numpy as np
import pandas as pd

In [6]:
enem_sp = pd.read_csv("enem_tratado.csv" , encoding="iso-8859-1")

In [7]:
enem_sp.head()

,NU_INSCRICAO,IDADE,SEXO,TP_ESTADO_CIVIL,RACA,TP_NACIONALIDADE,NO_MUNICIPIO_NASCIMENTO,TP_ST_CONCLUSAO,ESCOLA,CO_ESCOLA,...,NOTA_MT,TP_LINGUA,TP_STATUS_REDACAO,COMP1,COMP2,COMP3,COMP4,COMP5,NOTA_REDACAO,INTERNET
0,"1,90E+11",22,M,1,parda,1,Santa Izabel do Pará,1,Não respondeu,NaN,...,600.2,Inglês,1.0,160.0,200.0,180.0,200.0,200.0,940.0,Sim
1,"1,90E+11",19,M,1,parda,1,São Bernardo do Campo,2,Pública,35904958.0,...,393.2,espanhol,1.0,80.0,160.0,120.0,100.0,100.0,560.0,Sim
2,"1,90E+11",23,F,1,branco,1,São Paulo,1,Não respondeu,NaN,...,796.1,Inglês,1.0,160.0,200.0,180.0,180.0,160.0,880.0,Sim
3,"1,90E+11",18,F,1,branco,1,Belém,2,Pública,35028927.0,...,612.8,espanhol,1.0,120.0,160.0,120.0,80.0,100.0,580.0,Não
4,"1,90E+11",32,M,1,parda,1,Pratápolis,1,Não respondeu,NaN,...,584.1,espanhol,1.0,120.0,120.0,120.0,120.0,100.0,580.0,Sim

In [12]:
enem_campinas = enem_sp.loc[enem_sp.NO_MUNICIPIO_NASCIMENTO	 == 'Campinas']
enem_campinas.head(10)

,NU_INSCRICAO,IDADE,SEXO,TP_ESTADO_CIVIL,RACA,TP_NACIONALIDADE,NO_MUNICIPIO_NASCIMENTO,TP_ST_CONCLUSAO,ESCOLA,CO_ESCOLA,...,NOTA_MT,TP_LINGUA,TP_STATUS_REDACAO,COMP1,COMP2,COMP3,COMP4,COMP5,NOTA_REDACAO,INTERNET
69,"1,90E+11",18,M,1,branco,1,Campinas,2,Pública,35017632.0,...,508.2,espanhol,1.0,140.0,140.0,120.0,160.0,120.0,680.0,Sim
143,"1,90E+11",19,F,1,branco,1,Campinas,1,Não respondeu,NaN,...,628.5,Inglês,1.0,120.0,120.0,120.0,120.0,80.0,560.0,Sim
148,"1,90E+11",19,F,1,branco,1,Campinas,1,Não respondeu,NaN,...,378.6,Inglês,1.0,120.0,120.0,120.0,120.0,140.0,620.0,Sim
286,"1,90E+11",18,F,1,parda,1,Campinas,1,Não respondeu,NaN,...,605.3,Inglês,1.0,140.0,140.0,120.0,120.0,160.0,680.0,Sim
298,"1,90E+11",18,F,1,branco,1,Campinas,1,Não respondeu,NaN,...,68.6,Inglês,1.0,160.0,160.0,180.0,160.0,200.0,860.0,Sim
334,"1,90E+11",21,F,1,branco,1,Campinas,1,Não respondeu,NaN,...,554.3,espanhol,1.0,140.0,120.0,120.0,120.0,100.0,600.0,Sim
367,"1,90E+11",34,M,2,parda,1,Campinas,1,Não respondeu,NaN,...,630.8,Inglês,1.0,100.0,160.0,100.0,120.0,80.0,560.0,Sim
430,"1,90E+11",19,F,1,branco,1,Campinas,2,Pública,35058836.0,...,665.6,Inglês,1.0,160.0,200.0,160.0,180.0,140.0,840.0,Sim
492,"1,90E+11",39,F,1,branco,1,Campinas,1,Não respondeu,NaN,...,469.1,espanhol,1.0,80.0,120.0,120.0,120.0,120.0,560.0,Sim
562,"1,90E+11",18,M,1,branco,1,Campinas,2,Privada,NaN,...,604.8,Inglês,1.0,160.0,120.0,120.0,160.0,140.0,700.0,Sim

In [13]:
enem_campinas.shape

(9077, 28)